### get posts
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFqdSIsImlhdCI6MTc1MjI5MzQyOCwiZXhwIjoxNzUyMjkzNDU4fQ.oWeRENPrZxGaYLZYgF21UurMmufZ-hwzir1Ezpcea0k


###  login 
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Raju"
}

### refresh token
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFqdSIsImlhdCI6MTc1MjI5MzM2MH0.xg7lQ6Y5JXNy0SWYhhVhP6ShjFh3fW5Q2GzOmSU0FXo"
}

### logout
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFqdSIsImlhdCI6MTc1MjI5MzM2MH0.xg7lQ6Y5JXNy0SWYhhVhP6ShjFh3fW5Q2GzOmSU0FXo"
}
